### ISSUE TITLE
REW files not working ?

### ISSUE THREAD

**Issue by BonzaiMusik** [Tunetown/RoomMap#3]
Hey,
I wanted to try out this awesome programm but I'm import my REW .txt measurements and nothing shows up on RoomMap, yet when I import your examples files it works fine. Is there a particular setup for the REW export?
I'll link my files.

Thanks
[ExportForRoomMap.zip](https://github.com/Tunetown/RoomMap/files/6305172/ExportForRoomMap.zip)

**Comment by Tunetown** [comment]
Hi!

thanks for using the program :) i can have a look tomorrow, at first sight everything looks OK :) i will get back to you...have a nice evening in the meantime :)

Regards,
Tom

**Comment by BonzaiMusik** [comment]
Alright I hope we can work this out, if you need more informations on my setup let me know.

**Comment by Tunetown** [comment]
Hi!

i think i got the problem isolated: The program uses T-Spline Interpolators which unfortunately dont work when the third dimension is missing. Your dataset is only measured in the Z=0 plane (all the same height), but the interpolator expects 3-dimensional data. I was able to load your data anyway by tricking the program: just copying over all files to the Z=1 plane - so you have a fake 3D space, kind of. Just copy all files and use 1 as Z coordinate in the copied files. 

I uploaded the data with the copied files here, so you dont have to do it again: https://we.tl/t-2gHYna8HMA

However, the points are too far from each other to get good data above 150Hz (the program filters out data which does not make sense because of the Nyquist sampling theorem). Please do more measurements in a denser grid to get higher in frequency :) Play around with the frequency slider below 200Hz to see what i mean.

Have fun! And if you are Jesus, thanks a lot for your kind donation!

Cheers,
Tom
